'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {_electron}=require('./playwright.cjs');
(async()=>{
  const root=path.resolve(__dirname,'..');
  fs.mkdirSync(path.join(root,'.test-output'),{recursive:true});
  const userData=fs.mkdtempSync(path.join(root,'.test-output','desktop-'));
  const application=await _electron.launch({executablePath:require('electron'),args:[path.join(__dirname,'position-fixture.cjs')],env:{...process.env,SHOT_POSITION_TEST_DATA:userData,SHOT_TEST_SKIP_SHORTCUT:'1'}});
  try {
    const page=await application.firstWindow();
    await page.waitForSelector('body.desktop');
    await page.evaluate(()=>window.overlay.edit());
    await page.waitForFunction(()=>!document.body.classList.contains('view-only'));
    assert.equal(await page.locator('#map-workspace').isVisible(),true,'Map is the default tab');
    await page.locator('#calculator-tab').click();
    assert.equal(await application.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].isAlwaysOnTop()),true);
    const errors=[];page.on('pageerror',e=>errors.push(e.message));
    const paste=async(id,text)=>{await application.evaluate(({clipboard},value)=>clipboard.writeText(value),text);await page.locator('#'+id).focus();await page.keyboard.press('Control+A');await page.keyboard.press('Control+V');};
    await paste('player','Y102 X88');await paste('target','X72 Y80');
    await page.locator('#calculate-distance').click();
    assert.equal(await page.locator('#distance').inputValue(),'2720.29');
    assert.equal(await page.locator('#result').isVisible(),true);
    assert.match(await page.locator('#distance-value').textContent(),/2\s720,29/);
    assert.equal(await page.locator('#hit-distance').textContent(),'—');
    assert.equal(await page.locator('#aim-azimuth').textContent(),'216,0°');
    assert.equal(await page.locator('#hit-error').textContent(),'');
    await paste('target','x72, y80');
    assert.equal(await page.locator('#distance').inputValue(),'');
    await page.locator('#target').press('Enter');
    assert.equal(await page.locator('#distance').inputValue(),'2720.29');
    await paste('hit','Y93 X80');
    assert.equal(await page.locator('#distance').inputValue(),'2720.29');
    await page.locator('#hit').press('Enter');
    assert.match(await page.locator('#distance-value').textContent(),/6\s145,36/);
    await paste('distance','2720,29');
    await page.getByRole('button',{name:'Рассчитать поправку'}).click();
    assert.match(await page.locator('#aim-value').textContent(),/78,54/);
    assert.match(await page.locator('#distance-value').textContent(),/6\s145,36/);
    assert.equal(await page.locator('#aim-azimuth').textContent(),'210,4°');
    await page.locator('#copy').click();
    await page.waitForFunction(()=>document.getElementById('copy').textContent==='Скопировано');
    assert.equal(await application.evaluate(({clipboard})=>clipboard.readText()),'Y78.54 X74.23');
    await paste('hit','bad coordinate');assert.equal(await page.locator('#result').isVisible(),false);
    await page.getByRole('button',{name:'Рассчитать поправку'}).click();assert.equal(await page.locator('#hit').getAttribute('aria-invalid'),'true');
    await paste('hit','Y93 X80');await page.locator('#distance').fill('');await page.getByRole('button',{name:'Рассчитать поправку'}).click();
    assert.match(await page.locator('#distance-value').textContent(),/^× 2,26$/);
    await page.locator('#example').click();
    const scroll=await page.evaluate(()=>({width:document.documentElement.clientWidth,documentWidth:document.documentElement.scrollWidth}));assert.equal(scroll.width,scroll.documentWidth);
    fs.mkdirSync(path.join(root,'.test-output'),{recursive:true});
    await page.screenshot({path:path.join(root,'.test-output','overlay.png')});
    await page.locator('#hide-overlay').click();
    await page.waitForTimeout(150);
    assert.equal(await application.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].isVisible()),false);
    await application.evaluate(({BrowserWindow})=>{BrowserWindow.getAllWindows()[0].show();});
    assert.equal(await page.locator('#player').inputValue(),'Y102 X88');
    assert.deepEqual(errors,[]);
    console.log('PASS: base distance by click and Enter without hit; automatic baseline used for correction; stale baseline cleared after coordinate edit; correction by Enter; clipboard, validation, hide and preserved inputs.');
  }finally{await application.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
