'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {_electron}=require('./playwright.cjs');
const {coordToMap,mapToCoord}=require('../dist/maps.js');
(async()=>{
  assert.deepEqual(coordToMap({x:0,y:163.84}),{x:0,y:0});
  assert.deepEqual(mapToCoord({x:1000,y:1000}),{x:163.84,y:0});
  const root=path.resolve(__dirname,'..');fs.mkdirSync(path.join(root,'.test-output'),{recursive:true});
  const userData=fs.mkdtempSync(path.join(root,'.test-output','maps-'));
  const application=await _electron.launch({executablePath:require('electron'),args:[path.join(__dirname,'position-fixture.cjs')],env:{...process.env,SHOT_POSITION_TEST_DATA:userData,SHOT_TEST_SKIP_SHORTCUT:'1'}});
  try{
    const page=await application.firstWindow();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.waitForSelector('body.desktop');
    await page.waitForFunction(()=>document.body.classList.contains('view-only'));
    assert.equal(await application.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].isFocusable()),false);
    await page.evaluate(()=>window.overlay.edit());await page.waitForFunction(()=>!document.body.classList.contains('view-only'));
    assert.equal(await application.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].isFocusable()),true);
    const assets=await page.evaluate(async()=>Promise.all(['kavkazi','europe','northamerica'].map(id=>new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve([id,img.naturalWidth,img.naturalHeight]);img.onerror=()=>reject(Error(id));img.src='maps/'+id+'.webp';}))));
    for(const [,w,h]of assets){assert.equal(w,5120);assert.equal(h,5120);}
    await page.locator('#maps-tab').click();
    assert.equal(await page.locator('.spawn-base').count(),3);assert.equal(await page.locator('.control-zone').count(),1);
    assert.equal(await page.locator('#region-select').inputValue(),'bakurani');
    await page.locator('#region-select').selectOption('mindori');assert.equal(await page.locator('.spawn-base').count(),3);assert.equal(await page.locator('.control-zone').count(),0);
    await page.locator('#region-select').selectOption('bakurani');await page.locator('#reset-map').click();
    const place=async(value)=>{await page.locator('#map-coordinate').fill(value);await page.locator('#map-coordinate').press('Enter');};
    await place('x20, y20');await place('x40, y20');await place('x20, y50');
    assert.equal(await page.locator('.target-row').count(),2);assert.equal(await page.locator('#distance').inputValue(),'3000.00');
    await page.locator('.target-select').first().click();assert.equal(await page.locator('#distance').inputValue(),'2000.00');
    assert.equal(await page.locator('#distance-value').textContent(),'2 000 м');
    await page.locator('[data-map-tool="hit"]').click();await place('x30, y20');
    assert.equal(await page.locator('#distance-value').textContent(),'4 000 м');
    await page.locator('.target-select').nth(1).click();assert.equal(await page.locator('#hit').inputValue(),'');assert.equal(await page.locator('#distance').inputValue(),'3000.00');
    const goal1=page.locator('[data-target-id="1"]'),goal2=page.locator('[data-target-id="2"]');
    assert.equal(await goal1.locator('.target-coefficient').textContent(),'K ×2');
    assert.match(await goal1.locator('.target-power').textContent(),/^4\s000 м$/);
    assert.equal(await goal1.locator('.target-azimuth').textContent(),'090,0°');
    assert.equal(await goal2.locator('.target-azimuth').textContent(),'000,0°');
    assert.match(await page.locator('#fs-range').textContent(),/^3\s000 м$/,'Fire solution shows the selected goal');
    await place('x20, y60');
    assert.equal(await goal2.locator('.target-coefficient').textContent(),'K ×0,75');
    assert.match(await goal2.locator('.target-power').textContent(),/^2\s250 м$/);
    assert.equal(await goal1.locator('.target-coefficient').textContent(),'K ×2');
    assert.match(await page.locator('#fs-range').textContent(),/^2\s250 м$/);assert.equal(await page.locator('#fs-tag').isVisible(),true);
    await page.locator('.target-select').first().click();assert.equal(await page.locator('#hit').inputValue(),'x30.00, y20.00');
    await page.locator('#terrain-select').selectOption('europe');assert.equal(await page.locator('.target-row').count(),0);
    await page.locator('#terrain-select').selectOption('kavkazi');assert.equal(await page.locator('.target-row').count(),2);
    await page.locator('[data-map-tool="target"]').click();
    await page.locator('#reset-map').click();
    const bounds=await page.locator('#terrain').boundingBox();await page.mouse.click(bounds.x+bounds.width/2,bounds.y+bounds.height/2);
    assert.match(await goal1.locator('.target-power').textContent(),/^4\s000 м$/,'Adding another goal keeps first correction visible');
    assert.match(await goal2.locator('.target-power').textContent(),/^2\s250 м$/,'Second goal keeps its own coefficient');
    assert.equal(await page.locator('[data-target-id="3"] .target-coefficient').count(),0,'New goal inherits no correction');
    await page.screenshot({path:path.join(root,'.test-output','per-goal-corrections.png')});
    const clicked=require('../dist/app.js').parseCoordinate(await page.locator('#target').inputValue());
    assert.ok(Math.abs(clicked.x-81.92)<163.84/bounds.width&&Math.abs(clicked.y-81.92)<163.84/bounds.height,'Center click matches map coordinates within one screen pixel');
    await page.locator('#zoom-in').click();assert.notEqual(await page.locator('#terrain').getAttribute('viewBox'),'0 0 1000 1000');
    await page.locator('#reset-map').click();assert.equal(await page.locator('#terrain').getAttribute('viewBox'),'0 0 1000 1000');
    const counts=await page.locator('.target-row').count();await place('x999, y20');assert.equal(await page.locator('.target-row').count(),counts);assert.match(await page.locator('#map-error').textContent(),/163,84/);
    await page.locator('#terrain-select').selectOption('northamerica');await page.locator('#terrain-select').selectOption('kavkazi');
    await page.screenshot({path:path.join(root,'.test-output','maps.png')});
    await page.locator('#zoom-in').click();
    const beforePan=await page.locator('#terrain').getAttribute('viewBox');const box=await page.locator('#terrain').boundingBox();
    await page.mouse.move(box.x+box.width*.7,box.y+box.height*.7);await page.mouse.down();await page.mouse.move(box.x+box.width*.6,box.y+box.height*.6,{steps:8});await page.mouse.up();
    assert.notEqual(await page.locator('#terrain').getAttribute('viewBox'),beforePan);assert.equal(await page.locator('.target-row').count(),3,'Dragging in target mode does not place a target');
    await page.locator('#reset-map').click();
    const diameter=await page.locator('[data-marker="Цель 3"] circle').boundingBox();
    assert.ok(Math.abs(diameter.width-23.5)<1, JSON.stringify(diameter));
    await page.locator('#zoom-in').click();
    const zoomed=await page.locator('[data-marker="Цель 3"] circle').boundingBox();
    assert.ok(Math.abs(zoomed.width-diameter.width)<0.1,'SVG pin stays 22 screen pixels across zoom');
    assert.equal(await page.locator('[data-marker="Цель 3"] text').textContent(),'3');
    await page.locator('#reset-map').click();
    await page.locator('[data-marker="Цель 3"] circle').click();assert.equal(await page.locator('.target-row').count(),3,'Clicking the selected pin never deletes it');
    await page.keyboard.press('Delete');assert.equal(await page.locator('.target-row').count(),2,'Delete removes the selected goal');
    assert.match(await page.locator('#toast-text').textContent(),/Цель 3 удалена/);
    await page.keyboard.press('Control+z');assert.equal(await page.locator('.target-row').count(),3,'Ctrl+Z restores the goal');
    await page.keyboard.press('Delete');assert.equal(await page.locator('.target-row').count(),2);
    await page.locator('.target-select').first().click();
    const hitBox=await page.locator('#terrain').boundingBox();
    await page.mouse.click(hitBox.x+hitBox.width*30/163.84,hitBox.y+hitBox.height*(1-20/163.84),{button:'right'});
    assert.match(await page.locator('.target-row.selected .target-detail').textContent(),/K ×.*выстрел 2/,'Second impact chains from the corrected shot');
    assert.equal(await page.locator('#distance').inputValue(),'4000.00','Corrected range becomes the setting of the next shot');
    assert.equal(await page.locator('#previous-aim').inputValue(),'x40.00, y20.00','Corrected aim becomes the previous aim');
    assert.equal(await page.locator('.target-row').count(),2,'RMB records impact without creating goal');
    await page.locator('#reset-correction').click();assert.equal(await page.locator('#distance').inputValue(),'2000.00');assert.equal(await page.locator('#hit').inputValue(),'');
    await page.keyboard.press('Control+z');assert.notEqual(await page.locator('#hit').inputValue(),'','Undo restores the correction');
    await page.locator('[data-marker="Я"] circle').click();
    assert.equal(await page.locator('.target-row').count(),2);
    assert.equal(await page.locator('[data-map-tool="player"]').getAttribute('aria-pressed'),'true','Clicking own pin arms relocation instead of deleting it');
    assert.equal(await page.locator('#player').inputValue(),'x20.00, y20.00');
    await place('x25, y20');
    assert.equal(await page.locator('.target-row').count(),2);
    assert.equal(await page.locator('#distance').inputValue(),'1500.00');
    assert.equal(await page.locator('#hit').inputValue(),'');
    assert.match(await page.locator('.card-range').first().textContent(),/1.500/);
    await page.locator('.target-select').nth(1).click();
    assert.equal(await page.locator('#distance').inputValue(),'3041.38');
    await page.locator('[data-map-tool="player"]').click();await place('x20, y20');
    await page.locator('.target-select').first().click();
    await page.evaluate(()=>document.body.dispatchEvent(new KeyboardEvent('keydown',{key:'е',code:'KeyT',bubbles:true})));
    assert.equal(await page.locator('[data-map-tool="target"]').getAttribute('aria-pressed'),'true','Hotkeys use physical keys on the Russian layout');
    await page.locator('#compact-toggle').click();assert.equal(await page.locator('body.compact-map').count(),1);
    await page.locator('#compact-toggle').click();assert.equal(await page.locator('body.compact-map').count(),0);
    await application.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(480,820));await page.waitForFunction(()=>document.body.classList.contains('compact-map'));
    assert.equal(await page.locator('#compact-toggle').isDisabled(),true);
    const layout=await page.evaluate(()=>{const map=document.getElementById('terrain-frame').getBoundingClientRect(),cards=[...document.querySelectorAll('.target-row')].map(e=>{const r=e.getBoundingClientRect();return {top:r.top,left:r.left};});return {bottom:map.bottom,cards,overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth};});
    assert.ok(layout.cards[0].top>=layout.bottom);assert.ok(layout.cards[1].top>layout.cards[0].top);assert.ok(layout.cards[1].top-layout.cards[0].top<65);assert.equal(layout.overflow,false);
    await page.screenshot({path:path.join(root,'.test-output','compact-map.png')});
    await page.locator('[data-map-tool="target"]').click();
    for(let id=4;id<=10;id++)await place('x'+(30+id*5)+', y80');
    assert.equal(await page.locator('[data-marker="Цель 10"] text').textContent(),'10');
    const glyphSize=await page.locator('[data-marker="Цель 10"] text').evaluate(e=>parseFloat(getComputedStyle(e).fontSize)*e.getScreenCTM().a);
    assert.ok(Math.abs(glyphSize-11)<0.1,'Digit font stays 11 screen pixels');
    const widePin=await page.locator('[data-marker="Цель 10"] circle').boundingBox();
    await application.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(360,600));
    await page.waitForFunction(()=>innerWidth===360);
    await page.waitForTimeout(80);
    const narrowPin=await page.locator('[data-marker="Цель 10"] circle').boundingBox();
    assert.ok(Math.abs(narrowPin.width-widePin.width)<0.15,'Resize preserves marker size');
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
    await page.screenshot({path:path.join(root,'.test-output','slim-360.png')});
    const beforeHit=await page.locator('#hit').inputValue(),smallBox=await page.locator('#terrain').boundingBox();
    await page.mouse.move(smallBox.x+smallBox.width*.6,smallBox.y+smallBox.height*.6);
    await page.mouse.down({button:'right'});await page.mouse.move(smallBox.x+smallBox.width*.7,smallBox.y+smallBox.height*.7,{steps:8});await page.mouse.up({button:'right'});
    assert.equal(await page.locator('#hit').inputValue(),beforeHit,'Right drag does not record impact');
    await application.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(1080,850));await page.waitForFunction(()=>!document.body.classList.contains('compact-map'));
    await page.locator('#calculator-tab').click();await page.locator('#player').fill('x25, y20');await page.locator('#maps-tab').click();
    await page.locator('.target-select').first().click();assert.equal(await page.locator('#hit').inputValue(),'');assert.equal(await page.locator('#distance').inputValue(),'1500.00');
    await page.locator('#view-overlay').click();await page.waitForFunction(()=>document.body.classList.contains('view-only'));
    assert.equal(await application.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].isVisible()),true);
    assert.equal(await application.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].isFocusable()),false);
    assert.deepEqual(errors,[]);console.log('PASS: offline maps, coordinates/grid, map click, zoom, multiple goals, per-goal and chained corrections, Delete/undo, safe pin clicks, layout-independent hotkeys, map switching, validation and non-focusable view mode.');
  }finally{await application.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});

