'use strict';
// Builds the data the game-map layer matches the in-game map against, from the offline maps:
// - dist/zone-patches.js: the luminance of every control zone's bounding square, to recognise map and zone
//   from the circle interior;
// - dist/maps/terrain-<map>.png: the whole map's luminance at 1024² (16 m/px, grey), for the wide terrain search
//   (512² is too coarse to tell a map for sure: the right one led by 0.10–0.14 there, by 0.37–0.50 at 1024²);
//   decoding and shrinking the 5120² WebP at start-up took ~0.7 s per map.
// Needs Electron to decode WebP: pnpm zone-patches (rerun after changing maps or landmarks-data.js).
const {app,BrowserWindow}=require('electron');
const fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),SIZE=64,TERRAIN_SIZE=1024,WORLD=163.84;
app.setPath('userData',path.join(root,'.test-output','zone-patches-profile'));
const MAP_LANDMARKS=new Function(fs.readFileSync(path.join(root,'dist','landmarks-data.js'),'utf8')+';return MAP_LANDMARKS;')();

// Runs in the page: area-averaged downscale of each square, then Rec. 601 luma (same weights as discSample).
function render(url,squares,size){
  return new Promise((resolve,reject)=>{
    const img=new Image();
    img.onerror=()=>reject(new Error('Не удалось открыть карту'));
    img.onload=()=>{
      const out={},canvas=new OffscreenCanvas(size,size),g=canvas.getContext('2d',{willReadFrequently:true});
      g.imageSmoothingEnabled=true;g.imageSmoothingQuality='high';
      for(const s of squares){
        const k=img.width/s.world;g.clearRect(0,0,size,size);g.drawImage(img,s.x*k,(s.world-s.y)*k,s.size*k,s.size*k,0,0,size,size);
        const d=g.getImageData(0,0,size,size).data;let bin='';
        for(let i=0;i<size*size;i++)bin+=String.fromCharCode(Math.round(.299*d[i*4]+.587*d[i*4+1]+.114*d[i*4+2]));
        out[s.key]=btoa(bin);
      }
      resolve(out);
    };
    img.src=url;
  });
}
// Runs in the page: the map shrunk to size² like the layer does it (high-quality smoothing), as grey PNG bytes.
function terrain(url,size){
  return new Promise((resolve,reject)=>{
    const img=new Image();
    img.onerror=()=>reject(new Error('Не удалось открыть карту'));
    img.onload=async()=>{
      const canvas=new OffscreenCanvas(size,size),g=canvas.getContext('2d',{willReadFrequently:true});
      g.imageSmoothingEnabled=true;g.imageSmoothingQuality='high';g.drawImage(img,0,0,size,size);
      const px=g.getImageData(0,0,size,size),d=px.data;
      for(let i=0;i<d.length;i+=4){const l=Math.round(.299*d[i]+.587*d[i+1]+.114*d[i+2]);d[i]=d[i+1]=d[i+2]=l;d[i+3]=255;}
      g.putImageData(px,0,0);
      resolve(Array.from(new Uint8Array(await(await canvas.convertToBlob({type:'image/png'})).arrayBuffer())));
    };
    img.src=url;
  });
}
app.whenReady().then(async()=>{
  const win=new BrowserWindow({show:false});
  await win.loadURL('about:blank');
  for(const world of Object.keys(MAP_LANDMARKS)){
    const url='data:image/webp;base64,'+fs.readFileSync(path.join(root,'dist','maps',world+'.webp')).toString('base64');
    const png=Buffer.from(await win.webContents.executeJavaScript(`(${terrain})(${JSON.stringify(url)},${TERRAIN_SIZE})`));
    fs.writeFileSync(path.join(root,'dist','maps',`terrain-${world}.png`),png);
    console.log(`dist/maps/terrain-${world}.png: ${(png.length/1024).toFixed(0)} KB`);
  }
  const patches={};
  for(const [world,meta]of Object.entries(MAP_LANDMARKS)){
    // Top-left corner of each zone's bounding square in game units (Y grows to the north).
    const squares=meta.zones.map(z=>{const r=z.radiusM/100;return {key:`${world}/${z.id}`,x:z.pos[0]*WORLD-r,y:(1-z.pos[1])*WORLD+r,size:2*r,world:WORLD};});
    if(!squares.length)continue;
    const url='data:image/webp;base64,'+fs.readFileSync(path.join(root,'dist','maps',world+'.webp')).toString('base64');
    Object.assign(patches,await win.webContents.executeJavaScript(`(${render})(${JSON.stringify(url)},${JSON.stringify(squares)},${SIZE})`));
  }
  const body=Object.entries(patches).map(([key,value])=>`${JSON.stringify(key)}:${JSON.stringify(value)}`).join(',\n');
  fs.writeFileSync(path.join(root,'dist','zone-patches.js'),`'use strict';
// Generated by scripts/zone-patches.cjs from dist/maps/*.webp and landmarks-data.js. Do not edit.
// Luminance 0–255 of each control zone's bounding square (centre ± radius), ${SIZE}×${SIZE}, rows from the north-west corner, base64.
const ZONE_PATCHES={size:${SIZE},patches:{
${body}}};
if(typeof module!=='undefined')module.exports={ZONE_PATCHES};
`);
  console.log(`dist/zone-patches.js: ${Object.keys(patches).length} zones`);
  app.quit();
}).catch(error=>{console.error(error);app.exit(1);});
